#!/usr/bin/env bash

set -eu -o pipefail

function main {
  local new_project_name="${1:?'error: missing argument: project name must be provided!'}"
  local new_project_dir="$HOME/workspace/$new_project_name"
  local custom_archlinux_docker_dir="$HOME/workspace/github.com/nwmahoney/custom-archlinux-docker"

  mkdir "$new_project_dir"

  cp "$custom_archlinux_docker_dir/docker-compose.yml" "$new_project_dir"
  cp "$custom_archlinux_docker_dir/Dockerfile" "$new_project_dir"
  cp -r "$custom_archlinux_docker_dir/dotfiles" "$new_project_dir"
  cp -r "$custom_archlinux_docker_dir/scripts" "$new_project_dir"
  cp -r "$custom_archlinux_docker_dir/shared-dir" "$new_project_dir"

  rm "$new_project_dir/scripts/new_project"

  echo "initialized new project '$new_project_name' at '$new_project_dir'"
}

main "$@"
